编译报错：无法生成rootfs文件

报错表现：

```c++
ERROR: fsl-image-qt5-1.0-r0 do_rootfs: Error executing a python function in exec_python_func() autogenerated:

The stack trace of python calls that resulted in this exception/failure was:
File: 'exec_python_func() autogenerated', lineno: 2, function: <module>
     0001:
 *** 0002:license_create_manifest(d)
     0003:
File: '/home/alex/nfs_share/IMX_Platform/IMX6D/sdk/sources/poky/meta/classes/license.bbclass', lineno: 48, function: license_create_manifest
     0044:    pkg_dic = {}
     0045:    for pkg in sorted(image_list_installed_packages(d)):
     0046:        pkg_info = os.path.join(d.getVar('PKGDATA_DIR', True),
     0047:                                'runtime-reverse', pkg)
 *** 0048:        pkg_name = os.path.basename(os.readlink(pkg_info))
     0049:
     0050:        pkg_dic[pkg_name] = oe.packagedata.read_pkgdatafile(pkg_info)
     0051:        if not "LICENSE" in pkg_dic[pkg_name].keys():
     0052:            pkg_lic_name = "LICENSE_" + pkg_name
Exception: OSError: [Errno 2] No such file or directory: '/home/alex/nfs_share/IMX_Platform/IMX6D/sdk/bld-fb/tmp/sysroots/imx6dlsabresd/pkgdata/runtime-reverse/No'

ERROR: fsl-image-qt5-1.0-r0 do_rootfs: Function failed: license_create_manifest
ERROR: Logfile of failure stored in: /home/alex/nfs_share/IMX_Platform/IMX6D/sdk/bld-fb/tmp/work/imx6dlsabresd-poky-linux-gnueabi/fsl-image-qt5/1.0-r0/temp/log.do_rootfs.47482
ERROR: Task 9 (/home/alex/nfs_share/IMX_Platform/IMX6D/sdk/sources/meta-fsl-bsp-release/imx/meta-sdk/recipes-fsl/images/fsl-image-qt5.bb, do_rootfs) failed with exit code '1'
```

**无法解决此问题，随意更换4.14.98新内核版本进行编译**

参考文章：
https://patchwork.openembedded.org/patch/123001/